"""auto_20260606_123101

Revision ID: 03926033a2de
Revises: f314e78d9176
Create Date: 2026-06-06 12:31:01.515194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03926033a2de'
down_revision: Union[str, Sequence[str], None] = 'f314e78d9176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('dummy_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'dummy_test')
    # ### end Alembic commands ###
