"""auto_20260614_141121

Revision ID: 04ca79637e3f
Revises: cebc8066a727
Create Date: 2026-06-14 14:11:21.626425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ca79637e3f'
down_revision: Union[str, Sequence[str], None] = 'cebc8066a727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_has_modules_has_api_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'user_role_id', 'module_id', 'api_permission_id', name='uq_user_role_has_modules_has_api_perm')
    )
    op.create_index(op.f('ix_user_role_has_modules_has_api_permission_id'), 'user_role_has_modules_has_api_permission', ['id'], unique=False)
    op.create_table('user_role_has_modules_has_ui_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'user_role_id', 'module_id', 'ui_permission_id', name='uq_user_role_has_modules_has_ui_perm')
    )
    op.create_index(op.f('ix_user_role_has_modules_has_ui_permission_id'), 'user_role_has_modules_has_ui_permission', ['id'], unique=False)
    op.drop_index(op.f('ix_user_role_has_modules_id'), table_name='user_role_has_modules')
    op.drop_table('user_role_has_modules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_has_modules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('realm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('user_role_has_modules_application_id_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('user_role_has_modules_module_id_fkey')),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], name=op.f('user_role_has_modules_realm_id_fkey')),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], name=op.f('user_role_has_modules_user_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_role_has_modules_pkey')),
    sa.UniqueConstraint('realm_id', 'application_id', 'user_role_id', 'module_id', name=op.f('uq_user_role_has_modules'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_role_has_modules_id'), 'user_role_has_modules', ['id'], unique=False)
    op.drop_index(op.f('ix_user_role_has_modules_has_ui_permission_id'), table_name='user_role_has_modules_has_ui_permission')
    op.drop_table('user_role_has_modules_has_ui_permission')
    op.drop_index(op.f('ix_user_role_has_modules_has_api_permission_id'), table_name='user_role_has_modules_has_api_permission')
    op.drop_table('user_role_has_modules_has_api_permission')
    # ### end Alembic commands ###
