"""auto_20260606_123121

Revision ID: 0e65bb9b2800
Revises: 03926033a2de
Create Date: 2026-06-06 12:31:21.385307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e65bb9b2800'
down_revision: Union[str, Sequence[str], None] = '03926033a2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'dummy_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('dummy_test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
