"""auto_20260614_054557

Revision ID: 2d11b72227a1
Revises: fb77e6f89df7
Create Date: 2026-06-14 05:45:57.579654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d11b72227a1'
down_revision: Union[str, Sequence[str], None] = 'fb77e6f89df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_has_api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'api_permission_id', name='uq_module_has_api_permission')
    )
    op.create_index(op.f('ix_module_has_api_permissions_id'), 'module_has_api_permissions', ['id'], unique=False)
    op.create_table('module_has_ui_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'ui_permission_id', name='uq_module_has_ui_permission')
    )
    op.create_index(op.f('ix_module_has_ui_permissions_id'), 'module_has_ui_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_has_ui_permissions_id'), table_name='module_has_ui_permissions')
    op.drop_table('module_has_ui_permissions')
    op.drop_index(op.f('ix_module_has_api_permissions_id'), table_name='module_has_api_permissions')
    op.drop_table('module_has_api_permissions')
    # ### end Alembic commands ###
