"""auto_20260614_061746

Revision ID: 3a8cb4a66bd4
Revises: 291feaa2761c
Create Date: 2026-06-14 06:17:46.846796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8cb4a66bd4'
down_revision: Union[str, Sequence[str], None] = '291feaa2761c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_has_api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'api_permission_id', name='uq_app_has_api_permission')
    )
    op.create_index(op.f('ix_application_has_api_permissions_id'), 'application_has_api_permissions', ['id'], unique=False)
    op.create_table('application_has_ui_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'ui_permission_id', name='uq_app_has_ui_permission')
    )
    op.create_index(op.f('ix_application_has_ui_permissions_id'), 'application_has_ui_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_has_ui_permissions_id'), table_name='application_has_ui_permissions')
    op.drop_table('application_has_ui_permissions')
    op.drop_index(op.f('ix_application_has_api_permissions_id'), table_name='application_has_api_permissions')
    op.drop_table('application_has_api_permissions')
    # ### end Alembic commands ###
