"""remove_realm_and_app_from_permissions

Revision ID: 3d7882221c03
Revises: 86e6a969b4c8
Create Date: 2026-06-06 18:58:52.840423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7882221c03'
down_revision: Union[str, Sequence[str], None] = '86e6a969b4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_realm_permission_name'), 'api_permissions', type_='unique')
    op.create_unique_constraint(None, 'api_permissions', ['api_permission_name'])
    op.drop_constraint(op.f('api_permissions_application_id_fkey'), 'api_permissions', type_='foreignkey')
    op.drop_constraint(op.f('api_permissions_realm_id_fkey'), 'api_permissions', type_='foreignkey')
    op.drop_column('api_permissions', 'application_id')
    op.drop_column('api_permissions', 'realm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_permissions', sa.Column('realm_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('api_permissions', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('api_permissions_realm_id_fkey'), 'api_permissions', 'realms', ['realm_id'], ['id'])
    op.create_foreign_key(op.f('api_permissions_application_id_fkey'), 'api_permissions', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'api_permissions', type_='unique')
    op.create_unique_constraint(op.f('uq_realm_permission_name'), 'api_permissions', ['realm_id', 'api_permission_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
