"""create_api_permission_profile_table

Revision ID: 72496e71d8ab
Revises: 3d7882221c03
Create Date: 2026-06-06 19:38:07.787127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72496e71d8ab'
down_revision: Union[str, Sequence[str], None] = '3d7882221c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_permission_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'api_permission_id', name='uq_realm_app_permission')
    )
    op.create_index(op.f('ix_api_permission_profiles_id'), 'api_permission_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_permission_profiles_id'), table_name='api_permission_profiles')
    op.drop_table('api_permission_profiles')
    # ### end Alembic commands ###
