"""rename_api_permission_profile_to_application_has_api_permission

Revision ID: 78772a74ed08
Revises: 72496e71d8ab
Create Date: 2026-06-06 19:59:30.848690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78772a74ed08'
down_revision: Union[str, Sequence[str], None] = '72496e71d8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_has_api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'api_permission_id', name='uq_app_has_api_permission')
    )
    op.create_index(op.f('ix_application_has_api_permissions_id'), 'application_has_api_permissions', ['id'], unique=False)
    op.drop_index(op.f('ix_api_permission_profiles_id'), table_name='api_permission_profiles')
    op.drop_table('api_permission_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_permission_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('realm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], name=op.f('api_permission_profiles_api_permission_id_fkey')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('api_permission_profiles_application_id_fkey')),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], name=op.f('api_permission_profiles_realm_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_permission_profiles_pkey')),
    sa.UniqueConstraint('realm_id', 'application_id', 'api_permission_id', name=op.f('uq_realm_app_permission'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_api_permission_profiles_id'), 'api_permission_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_application_has_api_permissions_id'), table_name='application_has_api_permissions')
    op.drop_table('application_has_api_permissions')
    # ### end Alembic commands ###
