"""change_permission_unique_constraint

Revision ID: 86e6a969b4c8
Revises: e67c2ccffde3
Create Date: 2026-06-06 18:52:49.355801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e6a969b4c8'
down_revision: Union[str, Sequence[str], None] = 'e67c2ccffde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_permissions_api_permission_name_key'), 'api_permissions', type_='unique')
    op.create_unique_constraint('uq_realm_permission_name', 'api_permissions', ['realm_id', 'api_permission_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_realm_permission_name', 'api_permissions', type_='unique')
    op.create_unique_constraint(op.f('api_permissions_api_permission_name_key'), 'api_permissions', ['api_permission_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
