"""add_active_to_realms_has_applications

Revision ID: 874ab22ec3b0
Revises: e5ac9060972f
Create Date: 2026-06-22 04:49:36.208333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874ab22ec3b0'
down_revision: Union[str, Sequence[str], None] = 'e5ac9060972f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realms_has_applications', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realms_has_applications', 'active')
    # ### end Alembic commands ###
