"""auto_20260606_125204

Revision ID: bf00ecbb79ba
Revises: 0e65bb9b2800
Create Date: 2026-06-06 12:52:04.124672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf00ecbb79ba'
down_revision: Union[str, Sequence[str], None] = '0e65bb9b2800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realms_has_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_uuid', sa.String(), nullable=False),
    sa.Column('internal_application_uuid', sa.String(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_uuid'),
    sa.UniqueConstraint('internal_application_uuid')
    )
    op.create_index(op.f('ix_realms_has_applications_id'), 'realms_has_applications', ['id'], unique=False)
    op.drop_constraint(op.f('applications_internal_uuid_key'), 'applications', type_='unique')
    op.drop_constraint(op.f('applications_uuid_key'), 'applications', type_='unique')
    op.drop_constraint(op.f('applications_realm_id_fkey'), 'applications', type_='foreignkey')
    op.drop_column('applications', 'realm_id')
    op.drop_column('applications', 'internal_uuid')
    op.drop_column('applications', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('internal_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('realm_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('applications_realm_id_fkey'), 'applications', 'realms', ['realm_id'], ['id'])
    op.create_unique_constraint(op.f('applications_uuid_key'), 'applications', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('applications_internal_uuid_key'), 'applications', ['internal_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_realms_has_applications_id'), table_name='realms_has_applications')
    op.drop_table('realms_has_applications')
    # ### end Alembic commands ###
