"""auto_20260614_121528

Revision ID: cebc8066a727
Revises: 9741c6bca0b1
Create Date: 2026-06-14 12:15:28.877332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebc8066a727'
down_revision: Union[str, Sequence[str], None] = '9741c6bca0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_roles")
    op.add_column('user_roles', sa.Column('realm_id', sa.Integer(), nullable=False))
    op.add_column('user_roles', sa.Column('application_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_roles_role_name_key'), 'user_roles', type_='unique')
    op.create_unique_constraint('uq_user_roles', 'user_roles', ['realm_id', 'application_id', 'role_name'])
    op.create_foreign_key(None, 'user_roles', 'realms', ['realm_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint('uq_user_roles', 'user_roles', type_='unique')
    op.create_unique_constraint(op.f('user_roles_role_name_key'), 'user_roles', ['role_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_roles', 'application_id')
    op.drop_column('user_roles', 'realm_id')
    # ### end Alembic commands ###
