"""auto_20260616_024253

Revision ID: e5ac9060972f
Revises: b4b761c88406
Create Date: 2026-06-16 02:42:53.686440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ac9060972f'
down_revision: Union[str, Sequence[str], None] = 'b4b761c88406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_has_api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'api_permission_id', name='uq_app_has_api_permission')
    )
    op.create_index(op.f('ix_application_has_api_permissions_id'), 'application_has_api_permissions', ['id'], unique=False)
    op.create_table('application_has_ui_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'ui_permission_id', name='uq_app_has_ui_permission')
    )
    op.create_index(op.f('ix_application_has_ui_permissions_id'), 'application_has_ui_permissions', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('realms_has_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_uuid', sa.String(), nullable=False),
    sa.Column('internal_application_uuid', sa.String(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_uuid'),
    sa.UniqueConstraint('internal_application_uuid')
    )
    op.create_index(op.f('ix_realms_has_applications_id'), 'realms_has_applications', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'role_name', name='uq_user_roles')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('module_has_api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'api_permission_id', name='uq_module_has_api_permission')
    )
    op.create_index(op.f('ix_module_has_api_permissions_id'), 'module_has_api_permissions', ['id'], unique=False)
    op.create_table('module_has_ui_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'ui_permission_id', name='uq_module_has_ui_permission')
    )
    op.create_index(op.f('ix_module_has_ui_permissions_id'), 'module_has_ui_permissions', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'realm_id', 'application_id', 'user_role_id', name='uq_user_profile_composite')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_role_has_modules_has_api_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('api_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_permission_id'], ['api_permissions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'user_role_id', 'module_id', 'api_permission_id', name='uq_user_role_has_modules_has_api_perm')
    )
    op.create_index(op.f('ix_user_role_has_modules_has_api_permission_id'), 'user_role_has_modules_has_api_permission', ['id'], unique=False)
    op.create_table('user_role_has_modules_has_ui_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'user_role_id', 'module_id', 'ui_permission_id', name='uq_user_role_has_modules_has_ui_perm')
    )
    op.create_index(op.f('ix_user_role_has_modules_has_ui_permission_id'), 'user_role_has_modules_has_ui_permission', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_has_modules_has_ui_permission_id'), table_name='user_role_has_modules_has_ui_permission')
    op.drop_table('user_role_has_modules_has_ui_permission')
    op.drop_index(op.f('ix_user_role_has_modules_has_api_permission_id'), table_name='user_role_has_modules_has_api_permission')
    op.drop_table('user_role_has_modules_has_api_permission')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_module_has_ui_permissions_id'), table_name='module_has_ui_permissions')
    op.drop_table('module_has_ui_permissions')
    op.drop_index(op.f('ix_module_has_api_permissions_id'), table_name='module_has_api_permissions')
    op.drop_table('module_has_api_permissions')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_realms_has_applications_id'), table_name='realms_has_applications')
    op.drop_table('realms_has_applications')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_application_has_ui_permissions_id'), table_name='application_has_ui_permissions')
    op.drop_table('application_has_ui_permissions')
    op.drop_index(op.f('ix_application_has_api_permissions_id'), table_name='application_has_api_permissions')
    op.drop_table('application_has_api_permissions')
    # ### end Alembic commands ###
