"""Initial schema

Revision ID: f314e78d9176
Revises: 
Create Date: 2026-06-06 12:30:05.804954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f314e78d9176'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.add_column('applications', sa.Column('internal_uuid', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'applications', ['internal_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_column('applications', 'internal_uuid')
    op.create_table('user_role',
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_role_pkey'))
    )
    # ### end Alembic commands ###
