"""auto_20260611_081252

Revision ID: fb77e6f89df7
Revises: 78772a74ed08
Create Date: 2026-06-11 08:12:52.868489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb77e6f89df7'
down_revision: Union[str, Sequence[str], None] = '78772a74ed08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ui_permission_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ui_permission_name')
    )
    op.create_index(op.f('ix_ui_permissions_id'), 'ui_permissions', ['id'], unique=False)
    op.create_table('application_has_ui_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('ui_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realms.id'], ),
    sa.ForeignKeyConstraint(['ui_permission_id'], ['ui_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('realm_id', 'application_id', 'ui_permission_id', name='uq_app_has_ui_permission')
    )
    op.create_index(op.f('ix_application_has_ui_permissions_id'), 'application_has_ui_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_has_ui_permissions_id'), table_name='application_has_ui_permissions')
    op.drop_table('application_has_ui_permissions')
    op.drop_index(op.f('ix_ui_permissions_id'), table_name='ui_permissions')
    op.drop_table('ui_permissions')
    # ### end Alembic commands ###
